In [39]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [40]:
#Importing Dataset
df=pd.read_csv('spam.csv',encoding=('ISO-8859-1'))
df

,v1,v2,Unnamed: 2,Unnamed: 3,Unnamed: 4
0,ham,"Go until jurong point, crazy.. Available only ...",NaN,NaN,NaN
1,ham,Ok lar... Joking wif u oni...,NaN,NaN,NaN
2,spam,Free entry in 2 a wkly comp to win FA Cup fina...,NaN,NaN,NaN
3,ham,U dun say so early hor... U c already then say...,NaN,NaN,NaN
4,ham,"Nah I don't think he goes to usf, he lives aro...",NaN,NaN,NaN
...,...,...,...,...,...
5567,spam,This is the 2nd time we have tried 2 contact u...,NaN,NaN,NaN
5568,ham,Will Ì_ b going to esplanade fr home?,NaN,NaN,NaN
5569,ham,"Pity, * was in mood for that. So...any other s...",NaN,NaN,NaN
5570,ham,The guy did some bitching but I acted like i'd...,NaN,NaN,NaN
5571,ham,Rofl. Its true to its name,NaN,NaN,NaN

In [41]:
df.head()

,v1,v2,Unnamed: 2,Unnamed: 3,Unnamed: 4
0,ham,"Go until jurong point, crazy.. Available only ...",NaN,NaN,NaN
1,ham,Ok lar... Joking wif u oni...,NaN,NaN,NaN
2,spam,Free entry in 2 a wkly comp to win FA Cup fina...,NaN,NaN,NaN
3,ham,U dun say so early hor... U c already then say...,NaN,NaN,NaN
4,ham,"Nah I don't think he goes to usf, he lives aro...",NaN,NaN,NaN

In [42]:
df=df.drop('Unnamed: 2',axis=1)
df=df.drop('Unnamed: 3',axis=1)
df=df.drop('Unnamed: 4',axis=1)

In [ ]:
df.head()

     v1                                                 v2
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...

In [43]:
#importing necessary NLP libraries
import re             
import nltk
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
from nltk.stem import WordNetLemmatizer

In [44]:
corpus=[]

In [80]:
import nltk
nltk.download('wordnet')
import pandas as pd

# Example data
data = {'message': ['This is the first message.', 'Another message here.', 'And a third message.'],
        'label': ['spam', 'ham', 'ham']}
df = pd.DataFrame(data)


for i in range(0,len(df)):
    review=re.sub('[^a-zA-Z]','',df['message'][i])
    review=review.lower()
    review=review.split()
    review=[lemmatizer.lemmatize(word) for word in review if not word in stopwords.words('english')]
    review=' '.join(review)
    corpus.append(review)

[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!

In [72]:
df.head()
df

                      message label
0  This is the first message.  spam
1       Another message here.   ham
2        And a third message.   ham

In [48]:
from sklearn.feature_extraction.text import CountVectorizer

In [49]:
#countvectorizer is the library which helps in creating BOW. cv is the object
cv=CountVectorizer(max_features=1000)

In [50]:
#independent variabl
X=cv.fit_transform(corpus).toarray()

In [76]:
#creating one hot(dummy variables) vectors for target variable
y=pd.get_dummies(df['label'])  
X=pd.get_dummies(df['message'])
y=y.iloc[:,1].values

In [77]:
#Do the train test split
from sklearn.model_selection import train_test_split  
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=0)

In [78]:
#for this we will use Multinomial Bayes algorithm to determine the label
from sklearn.naive_bayes import MultinomialNB

In [57]:
spam_detect_model=MultinomialNB().fit(X_train,y_train)

In [58]:
y_pred=spam_detect_model.predict(X_test)

In [59]:
from sklearn.metrics import accuracy_score

In [79]:
print(accuracy_score(y_test,y_pred))

1.0